sudo: false
language: ruby
script: "bundle exec rake"

branches:
  only:
    - master
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby
  - jruby-head
  - rbx-3

matrix:
  allow_failures:
      - rvm: ruby-head
      - rvm: jruby-head
      - rvm: rbx-3

after_success:
  - export CODECLIMATE_REPO_TOKEN=9b56bc5e14a34f1925548f4e0c61b9afe6b6d6da6227738218c4a99c88c10c65
  - bundle exec codeclimate-test-reporter
