language: ruby
branches:
  only:
    - master
rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.4
  - 2.3.0
  - ruby-head
  - jruby-1.7.22
  - jruby-9.0.4.0
  - jruby-head
  - rbx-2.5.8
matrix:
  allow_failures:
      - rvm: ruby-head
      - rvm: jruby-head
script: "COVERAGE=true script/test_all 2>&1"
